../design/verilog/common_ip/fifo_mux_2_1.v
../design/verilog/common_ip/fifo_mux_8_1.v
../design/verilog/common_ip/fifo_mux_16_1.v
../design/verilog/common_ip/fifo_depth8.v
../design/verilog/common_ip/fifo_depth64.v
../design/verilog/L0/l0.v
../design/verilog/OFIFO/ofifo.v
../design/verilog/PE_array/mac.v
../design/verilog/PE_array/reconf_mac_tile.v
../design/verilog/PE_array/mac_row.v
../design/verilog/PE_array/mac_array.v
../design/verilog/SFU/sfu.v
../design/verilog/corelet.v
../design/verilog/memories/xmem_2048x32.v
../design/verilog/memories/pmem_16384x128.v
../design/verilog/core.v
./core_tb.v
